src/main/java/com/madsvyat/crud/model/SearchQuery.java
package com.madsvyat.crud.model;


public class SearchQuery {
    private String query;

    public String getQuery() {
        return query;
    }

    public void setQuery(String query) {
        this.query = query;
    }
}

src/main/java/com/madsvyat/crud/model/TableProperties.java
package com.madsvyat.crud.model;


public class TableProperties {

    private int usersOnPage;

    public TableProperties() {
        usersOnPage = 10;
    }

    public int getUsersOnPage() {
        return usersOnPage;
    }

    public void setUsersOnPage(int usersOnPage) {
        this.usersOnPage = usersOnPage;
    }
}

src/main/java/com/madsvyat/crud/model/User.java
package com.madsvyat.crud.model;

import javax.persistence.*;

import org.apache.solr.analysis.LowerCaseFilterFactory;
import org.apache.solr.analysis.StandardFilterFactory;
import org.apache.solr.analysis.StandardTokenizerFactory;
import org.hibernate.search.annotations.*;

import java.util.Date;


@Entity
@Indexed
@Table(name = "User")
@AnalyzerDef(name = "nameanalyzer",
        tokenizer = @TokenizerDef(factory = StandardTokenizerFactory.class),
        filters = {
                @TokenFilterDef(factory = LowerCaseFilterFactory.class),
                @TokenFilterDef(factory = StandardFilterFactory.class)
        })
public class User {
    long id;
    String name;
    int age;
    boolean isAdmin;
    Date createdDate;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getId() {
        return id;
    }

    @Column(nullable = false, length = 25)
    @Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
    @Analyzer(definition = "nameanalyzer")
    public String getName() {
        return name;
    }

    @Column
    public int getAge() {
        return age;
    }

    @Column(name = "isAdmin")
    public boolean isAdmin() {
        return isAdmin;
    }

    @PrePersist
    @Temporal(value = TemporalType.TIMESTAMP)
    @Column(name = "createdDate")
    public Date getCreatedDate() {
        return createdDate;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public void setAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}

src/main/java/com/madsvyat/crud/controller/UserController.java
package com.madsvyat.crud.controller;

import com.madsvyat.crud.model.SearchQuery;
import com.madsvyat.crud.model.TableProperties;
import com.madsvyat.crud.model.User;
import com.madsvyat.crud.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.util.StringUtils;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Controller
@RequestMapping("/users")
public class UserController {

    @Autowired
    private UserService userService;

    @RequestMapping({"/", "/listUsers"})
    public String listUsers(@RequestParam(required = false, value = "page", defaultValue = "1") int page,
                            @RequestParam(required = false, value = "usersOnPage", defaultValue = "15") int usersOnPage,
                            ModelMap map) {
        TableProperties tableProperties = new TableProperties();
        tableProperties.setUsersOnPage(usersOnPage);
        map.addAttribute("user", new User());
        map.addAttribute("searchQuery", new SearchQuery());
        map.addAttribute("pageIndex", page);
        map.addAttribute("tableProperties", tableProperties);
        map.addAttribute("pagesCount", userService.getPagesCount(tableProperties.getUsersOnPage()));
        map.addAttribute("usersList", userService.getUsersList(page, tableProperties.getUsersOnPage()));

        return "/users/listUsers";
    }

    @RequestMapping("/get/{userId}/")
    public String getUser(@PathVariable long userId,
                          @RequestParam(required = false, value = "page", defaultValue = "1") int page,
                          @RequestParam(required = false, value = "usersOnPage", defaultValue = "15") int usersOnPage,
                          ModelMap map) {
        User user = userService.getUser(userId);
        map.addAttribute("user", user);
        map.addAttribute("pageIndex", page);

        TableProperties tableProperties = new TableProperties();
        tableProperties.setUsersOnPage(usersOnPage);
        map.addAttribute("tableProperties", tableProperties);

        return "/users/userForm";
    }

    @RequestMapping("/emptyUserForm")
    public String getEmptyForm(@RequestParam(required = false, value = "page", defaultValue = "1") int page,
                               @RequestParam(required = false, value = "usersOnPage", defaultValue = "15") int usersOnPage,
                               ModelMap map) {
        map.addAttribute("user", new User());
        map.addAttribute("pageIndex", page);
        TableProperties tableProperties = new TableProperties();
        tableProperties.setUsersOnPage(usersOnPage);
        map.addAttribute("tableProperties", tableProperties);

        return "users/userForm";
    }

    @RequestMapping(value = "/save/{pageIndex}/", method = RequestMethod.POST)
    public String saveUser(@PathVariable int pageIndex, @ModelAttribute User user,
                          @RequestParam(required = false, value = "usersOnPage", defaultValue = "15") int usersOnPage,
                          ModelMap map) {
        userService.saveUser(user);
        TableProperties tableProperties = new TableProperties();
        map.addAttribute("tableProperties", tableProperties);

        return "redirect:/users/?page=" + pageIndex + "&usersOnPage=" + usersOnPage;
    }

    @RequestMapping(value = "/delete/{userId}")
    public String deleteUser(@PathVariable long userId,
                             @RequestParam(required = false, value = "page", defaultValue = "1") int page,
                             @RequestParam(required = false, value = "usersOnPage", defaultValue = "15") int usersOnPage) {
        userService.deleteUser(userId);

        return "redirect:/users/listUsers?page=" + page + "&usersOnPage=" + usersOnPage;
    }


    @RequestMapping(value = "/search", method = RequestMethod.POST)
    public String searchUser(@ModelAttribute SearchQuery searchQuery,
                             @RequestParam(required = false, value = "page", defaultValue = "1") int page,
                             @RequestParam(required = false, value = "usersOnPage", defaultValue = "15") int usersOnPage,
                             ModelMap map) {
        String query = searchQuery.getQuery().trim();
        if (StringUtils.isEmpty(query)) {
            return "redirect:/users/listUsers?page=" + page + "&usersOnPage=" + usersOnPage;
        }

        map.put("searchQuery", searchQuery);
        List<User> users = userService.searchUsersByName(query);
        map.put("usersList", users);
        map.addAttribute("user", new User());
        map.addAttribute("pageIndex", page);
        TableProperties tableProperties = new TableProperties();
        tableProperties.setUsersOnPage(usersOnPage);
        map.addAttribute("tableProperties", tableProperties);

        return "/users/searchResults";
    }
}

src/main/webapp/WEB-INF/views/users/listUsers.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8"/>
    <title>List Of Users</title>
    <link rel="stylesheet"
          href='<c:url value="/web-resources/css/bootstrap.css"/>'>
    <link rel="stylesheet"
          href='<c:url value="/web-resources/css/validation.css"/>'>
</head>
<body>

<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="#">Simplest CRUD webapp</a>
        <ul class="nav">
            <li class="active"><a href="/users/listUsers">Home</a></li>
            <li><a href="/">About</a></li>
        </ul>
    </div>
</div>


<div class="container">


    <div class="row">
        <div class="span4">
            <button class="btn" onclick="addUser(${pageIndex}, ${tableProperties.usersOnPage})"><i class="icon-plus"></i> Add User</button>
        </div>
        <div class="span8" align="right">
            <form:form cssClass="form-search" commandName="searchQuery" method="post" role="form"
                       action="/users/search?page=${pageIndex}&usersOnPage=${tableProperties.usersOnPage}">
                <form:input path="query" id="query" type="text" cssClass="input-medium search-query"></form:input>
                <button type="submit" class="btn">Search</button>
            </form:form>
        </div>
    </div>


    <div class="hide" id="userDialog">
    </div>

 <%--   <c:url var="actionUrl" value="/users/save/${pageIndex}&usersOnPage=${tableProperties.usersOnPage}"/> --%>

    <%-- TABLE --%>
    <div class="table-responsive">
        <table class="table table-bordered table-condensed table-hover ">
            <%--   <caption>Users list</caption> --%>
            <thead>
            <tr>
                <th>#</th>
                <th>Id</th>
                <th width="30%">Name</th>
                <th>Age</th>
                <th width="7%">Admin</th>
                <th>Created date</th>
                <th width="8%">Options</th>
            </tr>
            </thead>
            <tbody>
            <c:forEach items="${usersList}" var="user" varStatus="loopCounter">
                <tr>
                    <td><c:out value="${loopCounter.count + (pageIndex - 1) * tableProperties.usersOnPage}"/></td>
                    <td><c:out value="${user.id}"/></td>
                    <td><c:out value="${user.name}"/></td>
                    <td><c:out value="${user.age}"/></td>
                    <td>
                        <c:choose>
                            <c:when test="${user.admin}">
                                <img src="/web-resources/img/true.png" alt="true">
                            </c:when>
                            <c:otherwise>
                                <img src="/web-resources/img/false.png" alt="false">
                            </c:otherwise>
                        </c:choose></td>
                    <td>
                        <fmt:formatDate type="both" value="${user.createdDate}"/></td>
                    <td>
                        <nobr>
                            <a class="btn btn-primary btn-small"
                               onclick="editUser(${user.id}, ${pageIndex}, ${tableProperties.usersOnPage})">
                                <i class="icon-white icon-pencil"></i> Edit</a>
                            <a class="btn btn-danger btn-small"
                               href="delete/${user.id}/?page=${pageIndex}&usersOnPage=${tableProperties.usersOnPage}"
                               onclick="return confirm('Are you sure you want to delete this user?');">
                                <i class="icon-white icon-remove"></i> Delete</a>
                        </nobr>
                    </td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </div>

    <c:url var="firstUrl" value="/users/?page=1&usersOnPage=${tableProperties.usersOnPage}"/>
    <c:url var="lastUrl" value="/users/?page=${pagesCount}&usersOnPage=${tableProperties.usersOnPage}"/>
    <c:url var="prevUrl" value="/users/?page=${pageIndex - 1}&usersOnPage=${tableProperties.usersOnPage}"/>
    <c:url var="nextUrl" value="/users/?page=${pageIndex + 1}&usersOnPage=${tableProperties.usersOnPage}"/>

    <div class="row">
        <div class="span4">
            <label class="controls-row" for="usersOnPage">Users on page</label>
            <form:form commandName="tableProperties" method="post" role="form" action="/users/listUsers">
                <form:select path="usersOnPage" id="usersOnPage" cssClass="input-mini" onchange="this.form.submit()">
                    <form:option value="15">15</form:option>
                    <form:option value="20">20</form:option>
                    <form:option value="30">30</form:option>
                    <form:option value="50">50</form:option>
                </form:select>
            </form:form>
        </div>
        <div class="span8" align="right">
            <div class="pagination" align="right">
                <ul>
                    <c:choose>
                        <c:when test="${pageIndex == 1}">
                            <li class="disabled"><a href="#">&lt;&lt;</a></li>
                            <li class="disabled"><a href="#">&lt;</a></li>
                        </c:when>
                        <c:otherwise>
                            <li><a href="${firstUrl}">&lt;&lt;</a></li>
                            <li><a href="${prevUrl}">&lt;</a></li>
                        </c:otherwise>
                    </c:choose>
                    <c:forEach var="i" begin="1" end="${pagesCount}">
                        <c:url var="pageUrl" value="/users/?page=${i}&usersOnPage=${tableProperties.usersOnPage}"/>
                        <c:choose>
                            <c:when test="${i == pageIndex}">
                                <li class="active"><a href="${pageUrl}"><c:out value="${i}"/></a></li>
                            </c:when>
                            <c:otherwise>
                                <li><a href="${pageUrl}"><c:out value="${i}"/></a></li>
                            </c:otherwise>
                        </c:choose>
                    </c:forEach>
                    <c:choose>
                        <c:when test="${pageIndex == pagesCount}">
                            <li class="disabled"><a href="#">&gt;</a></li>
                            <li class="disabled"><a href="#">&gt;&gt;</a></li>
                        </c:when>
                        <c:otherwise>
                            <li><a href="${nextUrl}">&gt;</a></li>
                            <li><a href="${lastUrl}">&gt;&gt;</a></li>
                        </c:otherwise>
                    </c:choose>
                </ul>
            </div>
        </div>
    </div>

    <script type="text/javascript"
            src='<c:url value="/web-resources/js/lib/jquery-2.1.3.js"/>'></script>
    <script type="text/javascript"
            src='<c:url value="/web-resources/js/lib/jquery.validate.js"/>'></script>
    <script type="text/javascript"
            src='<c:url value="/web-resources/js/lib/bootstrap.js"/>'></script>
    <script type="text/javascript"
            src='<c:url value="/web-resources/js/js-for-listUsers.js"/>'></script>
</div>
</body>
</html>

src/main/webapp/WEB-INF/views/users/searchResults.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE HTML>
<html lang="en">
<html>
<head>
    <title>Search results</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8"/>
    <link rel="stylesheet"
          href='<c:url value="/web-resources/css/bootstrap.css"/>'>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="#">Simplest CRUD webapp</a>
        <ul class="nav">
            <li>
                <a href="/users/listUsers?page=${pageIndex}&usersOnPage=${tableProperties.usersOnPage}">Home</a>
            </li>
            <li class="active">
                <a href="#">Search results</a>
            </li>
            <li>
                <a href="/">About</a>
            </li>
        </ul>
    </div>
</div>

<c:set var="count" value="${usersList.size()}"/>

<div class="hide" id="userDialog">
</div>

<div class="container">
    <h4>Results for <i>${searchQuery.query}</i></h4>
    <c:choose>
        <c:when test="${count == 0}">
            No users with name <i>${searchQuery.query}</i> found
        </c:when>
        <c:otherwise>
            Found ${count} users
            <div class="table-responsive">
                <table class="table table-bordered table-condensed table-hover ">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Id</th>
                        <th width="30%">Name</th>
                        <th>Age</th>
                        <th width="7%">Admin</th>
                        <th>Created date</th>
                        <th width="8%">Options</th>
                    </tr>
                    </thead>
                    <tbody>
                    <c:forEach items="${usersList}" var="user" varStatus="loopCounter">
                        <tr>
                            <td><c:out value="${loopCounter.count}"/></td>
                            <td><c:out value="${user.id}"/></td>
                            <td><c:out value="${user.name}"/></td>
                            <td><c:out value="${user.age}"/></td>
                            <td>
                                <c:choose>
                                    <c:when test="${user.admin}">
                                        <img src="/web-resources/img/true.png" alt="true">
                                    </c:when>
                                    <c:otherwise>
                                        <img src="/web-resources/img/false.png" alt="false">
                                    </c:otherwise>
                                </c:choose></td>
                            <td>
                                <fmt:formatDate type="both" value="${user.createdDate}"/></td>
                            <td>
                                <nobr>
                                    <a class="btn btn-primary btn-small"
                                       onclick="editUser(${user.id}, ${pageIndex}, ${tableProperties.usersOnPage})">
                                        <i class="icon-white icon-pencil"></i> Edit</a>
                                    <a class="btn btn-danger btn-small"
                                       href="delete/${user.id}/?page=${pageIndex}&usersOnPage=${tableProperties.usersOnPage}"
                                       onclick="return confirm('Are you sure you want to delete this user?');">
                                        <i class="icon-white icon-remove"></i> Delete</a>
                                </nobr>
                            </td>
                        </tr>
                    </c:forEach>
                    </tbody>
                </table>
            </div>
        </c:otherwise>
    </c:choose>
    <br>
    <a href="/users/listUsers?page=${pageIndex}&usersOnPage=${tableProperties.usersOnPage}">Back to users list</a>
</div>

<script type="text/javascript"
        src='<c:url value="/web-resources/js/lib/jquery-2.1.3.js"/>'></script>
<script type="text/javascript"
        src='<c:url value="/web-resources/js/lib/jquery.validate.js"/>'></script>
<script type="text/javascript"
        src='<c:url value="/web-resources/js/lib/bootstrap.js"/>'></script>
<script type="text/javascript"
        src='<c:url value="/web-resources/js/js-for-listUsers.js"/>'></script>
</body>
</html>

src/main/webapp/WEB-INF/views/users/userForm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE HTML>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8"/>
    <link rel="stylesheet"
          href='<c:url value="/web-resources/css/bootstrap.css"/>'>
    <link rel="stylesheet"
          href='<c:url value="/web-resources/css/validation.css"/>'>
</head>
<body>

<c:url var="actionUrl" value="/users/save/${pageIndex}/?usersOnPage=${tableProperties.usersOnPage}"/>

<div id="userDialog" class="modal" role="dialog">
    <div class="modal-header">
        <h3>Save user</h3>
    </div>
    <div class="modal-body container">
        <div class="row-fluid">
            <div class="span6">
                <div class="area">
                    <form:form cssClass="form-horizontal" id="userForm" commandName="user" method="post" role="form"
                               action="${actionUrl}">
                        <div class="control-group">
                            <label class="control-label" for=
                                    "name">Username</label>
                            <div class="controls">
                                <form:input path="name" id="name" placeholder=
                                        "User name" type="text"/>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="age">Age</label>
                            <div class="controls">
                                <form:input name="age" id="age" path="age" placeholder=
                                        "0" type="text"/>
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="controls">
                                <label class="checkbox">
                                    <form:checkbox path="admin" name="admin"/>
                                    Admin</label>
                            </div>
                        </div>
                        <form:input path="id" type="hidden"/>
                    </form:form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="reset" class="btn btn-default" data-dismiss="modal">Dismiss</button>
        <button type="submit" class="btn btn-success" onclick="submitSaveForm()">Save User</button>
    </div>
</div>

<!--  It is advised to put the <script> tags at the end of the document body so they don't block rendering of the page -->
<script type="text/javascript"
        src='<c:url value="/web-resources/js/lib/jquery-2.1.3.js"/>'></script>
<script type="text/javascript"
        src='<c:url value="/web-resources/js/lib/jquery.validate.js"/>'></script>
<script type="text/javascript"
        src='<c:url value="/web-resources/js/lib/bootstrap.js"/>'></script>
<script type="text/javascript"
        src='<c:url value="/web-resources/js/js-for-listUsers.js"/>'></script>
</body>
</html>

src/main/webapp/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE HTML>
<html lang="en">
<html>
<head>
    <title>About</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8"/>
    <link rel="stylesheet"
          href='<c:url value="/web-resources/css/bootstrap.css"/>'>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="#">Simplest CRUD webapp</a>
        <ul class="nav">
            <li>
                <a href="/users/listUsers">Home</a>
            </li>
            <li class="active">
            <a href="index.jsp">About</a>
        </li>
        </ul>
    </div>
</div>
<div class="container">
    <h2>Тестовое задание</h2>
    <h5>Небольшие соображения:</h5>
    <ul >
        <li >Не уверен, нужно ли было после добавления пользователя делать переход на последнюю страницу,
            чтобы убедиться, что он добавлен нормально. Вообщем, этот переход делать не стал.</li>
        <li>При сохранении/удалении пользователя на странице с результатами поиска осущеставляется переход на предыдущую страницу.
        Хорошо это или плохо, тоже не могу сказать.</li>
        <li>Толком не въехал в Hibernate Search, поэтому поиск получился самый простой: по полю 'name'</li>
        <li>Использовал Bootstrap версии 2.3.2, а не последней. Чисто случайно наткнулся на версию 2.3.2 и ее документацию,
            потом переходить на последнюю стало лень, итак потратил большую часть времени на UI</li>
    </ul>
    <br>
    CRUD непосредственно <a href="/users/listUsers">находится здесь</a>
</div>
</body>
</html>